version: '3.7'

services:
  database:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 54320:5432
    volumes:
    - slim-app-pgdata:/var/lib/postgresql/data
volumes:
  slim-app-pgdata:
