name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: secret

    steps:
      - uses: actions/checkout@v3
      - run: make install
      - run: make migrate
      - run: make lint
      - run: make test

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
