name: Build
on: [push]

env:
  POSTGRES_PASSWORD: secret
  DB_HOST: postgres
  DB_PORT: 5432
  DB_DATABASE: postgres
  DB_USERNAME: postgres
  DB_PASSWORD: ${POSTGRES_PASSWORD}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: make install
      - run: make migrate
      - run: make lint
      - run: make test

    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
